from __future__ import annotations
import json, secrets
from datetime import datetime, timezone
from typing import Any, Optional
from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine
from .config import DATABASE_URL

def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()

def _normalize_db_url(url: str) -> str:
    if url.startswith("postgres://"):
        return "postgresql+psycopg://" + url[len("postgres://"):]
    if url.startswith("postgresql://") and "+" not in url.split("://", 1)[0]:
        return "postgresql+psycopg://" + url[len("postgresql://"):]
    return url

DB_URL = _normalize_db_url(DATABASE_URL)
_engine_kwargs: dict[str, Any] = {"pool_pre_ping": True}
if DB_URL.startswith("sqlite:"):
    _engine_kwargs["connect_args"] = {"check_same_thread": False}
ENGINE: Engine = create_engine(DB_URL, **_engine_kwargs)

def connect():
    return ENGINE.begin()

def init_db():
    statements = [
        """CREATE TABLE IF NOT EXISTS purchases (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          access_token TEXT UNIQUE NOT NULL,
          email TEXT,
          status TEXT NOT NULL DEFAULT 'pending',
          amount_cents INTEGER NOT NULL,
          currency TEXT NOT NULL DEFAULT 'usd',
          stripe_session_id TEXT UNIQUE,
          acquisition_json TEXT NOT NULL DEFAULT '{}',
          created_at TEXT NOT NULL,
          paid_at TEXT
        )""",
        """CREATE TABLE IF NOT EXISTS assessments (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          purchase_id INTEGER NOT NULL UNIQUE,
          answers_json TEXT NOT NULL,
          result_json TEXT NOT NULL,
          created_at TEXT NOT NULL,
          FOREIGN KEY(purchase_id) REFERENCES purchases(id)
        )""",
        """CREATE TABLE IF NOT EXISTS feedback (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          purchase_id INTEGER NOT NULL,
          day INTEGER NOT NULL,
          payload_json TEXT NOT NULL,
          created_at TEXT NOT NULL,
          UNIQUE(purchase_id, day),
          FOREIGN KEY(purchase_id) REFERENCES purchases(id)
        )""",
        "CREATE INDEX IF NOT EXISTS idx_purchase_status ON purchases(status)",
        "CREATE INDEX IF NOT EXISTS idx_purchase_created ON purchases(created_at)",
    ]
    if DB_URL.startswith("sqlite:"):
        statements[0] = statements[0].replace("INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", "INTEGER PRIMARY KEY AUTOINCREMENT")
        statements[1] = statements[1].replace("INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", "INTEGER PRIMARY KEY AUTOINCREMENT")
        statements[2] = statements[2].replace("INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", "INTEGER PRIMARY KEY AUTOINCREMENT")
    with ENGINE.begin() as conn:
        for stmt in statements:
            conn.execute(text(stmt))

def _rowdict(row) -> dict | None:
    return dict(row._mapping) if row else None

def create_purchase(amount_cents: int, acquisition: dict[str, Any], email: str | None = None, status: str = "pending") -> dict:
    token = secrets.token_urlsafe(24)
    created = now_iso()
    params = {"token":token,"email":email,"status":status,"amount":amount_cents,"acq":json.dumps(acquisition),"created":created,"paid":created if status == 'paid' else None}
    with ENGINE.begin() as conn:
        if DB_URL.startswith("sqlite:"):
            res = conn.execute(text("INSERT INTO purchases(access_token,email,status,amount_cents,acquisition_json,created_at,paid_at) VALUES(:token,:email,:status,:amount,:acq,:created,:paid)"), params)
            pid = res.lastrowid
        else:
            pid = conn.execute(text("INSERT INTO purchases(access_token,email,status,amount_cents,acquisition_json,created_at,paid_at) VALUES(:token,:email,:status,:amount,:acq,:created,:paid) RETURNING id"), params).scalar_one()
    return {"id": pid, "access_token": token, "status": status}

def set_stripe_session(purchase_id: int, session_id: str):
    with ENGINE.begin() as conn:
        conn.execute(text("UPDATE purchases SET stripe_session_id=:sid WHERE id=:id"), {"sid":session_id,"id":purchase_id})

def mark_paid_by_session(session_id: str, email: str | None = None):
    with ENGINE.begin() as conn:
        conn.execute(text("UPDATE purchases SET status='paid', paid_at=:paid, email=COALESCE(:email,email) WHERE stripe_session_id=:sid"), {"paid":now_iso(),"email":email,"sid":session_id})

def get_purchase_by_token(token: str) -> Optional[dict]:
    with ENGINE.connect() as conn:
        row = conn.execute(text("SELECT * FROM purchases WHERE access_token=:token"), {"token":token}).fetchone()
    return _rowdict(row)

def get_purchase_by_session(session_id: str) -> Optional[dict]:
    with ENGINE.connect() as conn:
        row = conn.execute(text("SELECT * FROM purchases WHERE stripe_session_id=:sid"), {"sid":session_id}).fetchone()
    return _rowdict(row)

def save_assessment(purchase_id: int, answers: dict, result: dict):
    params={"pid":purchase_id,"answers":json.dumps(answers),"result":json.dumps(result),"created":now_iso()}
    with ENGINE.begin() as conn:
        if DB_URL.startswith("sqlite:"):
            conn.execute(text("INSERT INTO assessments(purchase_id,answers_json,result_json,created_at) VALUES(:pid,:answers,:result,:created) ON CONFLICT(purchase_id) DO UPDATE SET answers_json=excluded.answers_json,result_json=excluded.result_json,created_at=excluded.created_at"), params)
        else:
            conn.execute(text("INSERT INTO assessments(purchase_id,answers_json,result_json,created_at) VALUES(:pid,:answers,:result,:created) ON CONFLICT(purchase_id) DO UPDATE SET answers_json=EXCLUDED.answers_json,result_json=EXCLUDED.result_json,created_at=EXCLUDED.created_at"), params)

def get_assessment_for_purchase(purchase_id: int) -> Optional[dict]:
    with ENGINE.connect() as conn:
        row = conn.execute(text("SELECT * FROM assessments WHERE purchase_id=:pid"), {"pid":purchase_id}).fetchone()
    if not row: return None
    d = _rowdict(row); d["answers"] = json.loads(d.pop("answers_json")); d["result"] = json.loads(d.pop("result_json")); return d

def save_feedback(purchase_id: int, day: int, payload: dict):
    params={"pid":purchase_id,"day":day,"payload":json.dumps(payload),"created":now_iso()}
    with ENGINE.begin() as conn:
        if DB_URL.startswith("sqlite:"):
            conn.execute(text("INSERT INTO feedback(purchase_id,day,payload_json,created_at) VALUES(:pid,:day,:payload,:created) ON CONFLICT(purchase_id,day) DO UPDATE SET payload_json=excluded.payload_json,created_at=excluded.created_at"), params)
        else:
            conn.execute(text("INSERT INTO feedback(purchase_id,day,payload_json,created_at) VALUES(:pid,:day,:payload,:created) ON CONFLICT(purchase_id,day) DO UPDATE SET payload_json=EXCLUDED.payload_json,created_at=EXCLUDED.created_at"), params)

def admin_summary() -> dict:
    with ENGINE.connect() as conn:
        p = conn.execute(text("SELECT COUNT(*) AS total, SUM(CASE WHEN status='paid' THEN 1 ELSE 0 END) AS paid, SUM(CASE WHEN status='paid' THEN amount_cents ELSE 0 END) AS revenue_cents FROM purchases")).fetchone()
        a = conn.execute(text("SELECT COUNT(*) AS total FROM assessments")).fetchone()
        f = conn.execute(text("SELECT day, COUNT(*) AS c FROM feedback GROUP BY day ORDER BY day")).fetchall()
    pm = p._mapping; am=a._mapping
    total = pm['total'] or 0; paid = pm['paid'] or 0; assessments = am['total'] or 0
    return {
        "purchases": total, "paid": paid, "revenue_cents": pm['revenue_cents'] or 0,
        "assessment_completions": assessments,
        "paid_to_assessment_rate": round((assessments/paid*100), 1) if paid else 0,
        "feedback": {str(row._mapping['day']): row._mapping['c'] for row in f},
    }
