from __future__ import annotations

import hashlib
import json
import secrets
from datetime import datetime, timedelta, timezone
from typing import Any, Optional

from sqlalchemy import create_engine, inspect, text
from sqlalchemy.engine import Engine

from .config import DATABASE_URL
from .security import decrypt_json, encrypt_json


class DuplicateConsultationFingerprint(RuntimeError):
    pass


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _token_digest(token: str) -> str:
    return "sha256:" + hashlib.sha256(token.encode("utf-8")).hexdigest()


def _normalize_db_url(url: str) -> str:
    if url.startswith("postgres://"):
        return "postgresql+psycopg://" + url[len("postgres://"):]
    if url.startswith("postgresql://") and "+" not in url.split("://", 1)[0]:
        return "postgresql+psycopg://" + url[len("postgresql://"):]
    return url


DB_URL = _normalize_db_url(DATABASE_URL)
_engine_kwargs: dict[str, Any] = {"pool_pre_ping": True}
if DB_URL.startswith("sqlite:"):
    _engine_kwargs["connect_args"] = {"check_same_thread": False}
ENGINE: Engine = create_engine(DB_URL, **_engine_kwargs)


def connect():
    return ENGINE.begin()


def _ensure_purchase_columns() -> None:
    columns = {col["name"] for col in inspect(ENGINE).get_columns("purchases")}
    additions = {
        "stripe_payment_intent_id": "TEXT",
        "access_revoked_at": "TEXT",
        "access_revoked_reason": "TEXT",
    }
    for name, ddl in additions.items():
        if name in columns:
            continue
        with ENGINE.begin() as conn:
            conn.execute(text(f"ALTER TABLE purchases ADD COLUMN {name} {ddl}"))


def init_db():
    statements = [
        """CREATE TABLE IF NOT EXISTS purchases (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          access_token TEXT UNIQUE NOT NULL,
          email TEXT,
          status TEXT NOT NULL DEFAULT 'pending',
          amount_cents INTEGER NOT NULL,
          currency TEXT NOT NULL DEFAULT 'usd',
          stripe_session_id TEXT UNIQUE,
          stripe_payment_intent_id TEXT,
          access_revoked_at TEXT,
          access_revoked_reason TEXT,
          acquisition_json TEXT NOT NULL DEFAULT '{}',
          created_at TEXT NOT NULL,
          paid_at TEXT
        )""",
        """CREATE TABLE IF NOT EXISTS assessments (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          purchase_id INTEGER NOT NULL UNIQUE,
          answers_json TEXT NOT NULL,
          result_json TEXT NOT NULL,
          created_at TEXT NOT NULL,
          FOREIGN KEY(purchase_id) REFERENCES purchases(id)
        )""",
        """CREATE TABLE IF NOT EXISTS feedback (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          purchase_id INTEGER NOT NULL,
          day INTEGER NOT NULL,
          payload_json TEXT NOT NULL,
          created_at TEXT NOT NULL,
          UNIQUE(purchase_id, day),
          FOREIGN KEY(purchase_id) REFERENCES purchases(id)
        )""",
        """CREATE TABLE IF NOT EXISTS assessment_drafts (
          purchase_id INTEGER PRIMARY KEY,
          answers_json TEXT NOT NULL,
          current_index INTEGER NOT NULL DEFAULT 0,
          updated_at TEXT NOT NULL,
          FOREIGN KEY(purchase_id) REFERENCES purchases(id)
        )""",
        """CREATE TABLE IF NOT EXISTS consultation_fingerprints (
          fingerprint TEXT PRIMARY KEY,
          created_at TEXT NOT NULL
        )""",
        """CREATE TABLE IF NOT EXISTS consultation_fragment_fingerprints (
          fingerprint TEXT PRIMARY KEY,
          created_at TEXT NOT NULL
        )""",
        "CREATE INDEX IF NOT EXISTS idx_purchase_status ON purchases(status)",
        "CREATE INDEX IF NOT EXISTS idx_purchase_created ON purchases(created_at)",
        "CREATE INDEX IF NOT EXISTS idx_purchase_payment_intent ON purchases(stripe_payment_intent_id)",
    ]
    if DB_URL.startswith("sqlite:"):
        for idx in range(3):
            statements[idx] = statements[idx].replace(
                "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
                "INTEGER PRIMARY KEY AUTOINCREMENT",
            )

    with ENGINE.begin() as conn:
        for stmt in statements[:-1]:
            conn.execute(text(stmt))

    _ensure_purchase_columns()

    # Index creation must happen after legacy tables receive the new column.
    with ENGINE.begin() as conn:
        conn.execute(text(statements[-1]))


def _rowdict(row) -> dict | None:
    return dict(row._mapping) if row else None


def create_purchase(
    amount_cents: int,
    acquisition: dict[str, Any],
    email: str | None = None,
    status: str = "pending",
    currency: str = "usd",
) -> dict:
    token = secrets.token_urlsafe(24)
    created = now_iso()
    params = {
        "token": _token_digest(token),
        "email": email,
        "status": status,
        "amount": amount_cents,
        "currency": (currency or "usd").lower(),
        "acq": json.dumps(acquisition),
        "created": created,
        "paid": created if status == "paid" else None,
    }
    with ENGINE.begin() as conn:
        if DB_URL.startswith("sqlite:"):
            res = conn.execute(
                text(
                    "INSERT INTO purchases(access_token,email,status,amount_cents,currency,acquisition_json,created_at,paid_at) "
                    "VALUES(:token,:email,:status,:amount,:currency,:acq,:created,:paid)"
                ),
                params,
            )
            pid = res.lastrowid
        else:
            pid = conn.execute(
                text(
                    "INSERT INTO purchases(access_token,email,status,amount_cents,currency,acquisition_json,created_at,paid_at) "
                    "VALUES(:token,:email,:status,:amount,:currency,:acq,:created,:paid) RETURNING id"
                ),
                params,
            ).scalar_one()
    return {"id": pid, "access_token": token, "status": status}


def set_stripe_session(purchase_id: int, session_id: str):
    with ENGINE.begin() as conn:
        conn.execute(
            text("UPDATE purchases SET stripe_session_id=:sid WHERE id=:id"),
            {"sid": session_id, "id": purchase_id},
        )


def set_payment_intent(purchase_id: int, payment_intent_id: str | None):
    if not payment_intent_id:
        return
    with ENGINE.begin() as conn:
        conn.execute(
            text("UPDATE purchases SET stripe_payment_intent_id=:pi WHERE id=:id"),
            {"pi": payment_intent_id, "id": purchase_id},
        )


def mark_paid_by_session(session_id: str, payment_intent_id: str | None = None):
    # Webhook retries must not extend the access window or reactivate refunds/disputes.
    with ENGINE.begin() as conn:
        conn.execute(
            text(
                """
                UPDATE purchases
                SET status=CASE WHEN status='pending' THEN 'paid' ELSE status END,
                    paid_at=COALESCE(paid_at,:paid),
                    email=NULL,
                    stripe_payment_intent_id=COALESCE(:pi,stripe_payment_intent_id)
                WHERE stripe_session_id=:sid
                """
            ),
            {"paid": now_iso(), "sid": session_id, "pi": payment_intent_id},
        )


def recover_paid_purchase(
    session_id: str,
    access_token: str | None,
    amount_cents: int,
    currency: str = "usd",
    email: str | None = None,
    payment_intent_id: str | None = None,
) -> dict | None:
    paid = now_iso()
    access_token = access_token or secrets.token_urlsafe(24)
    params = {
        "sid": session_id,
        "pi": payment_intent_id,
        "token": _token_digest(access_token),
        "amount": amount_cents,
        "currency": currency or "usd",
        "created": paid,
        "paid": paid,
    }
    with ENGINE.begin() as conn:
        by_session = conn.execute(
            text("SELECT id,status FROM purchases WHERE stripe_session_id=:sid"),
            {"sid": session_id},
        ).fetchone()
        if by_session:
            conn.execute(
                text(
                    """
                    UPDATE purchases
                    SET status=CASE WHEN status='pending' THEN 'paid' ELSE status END,
                        paid_at=COALESCE(paid_at,:paid),
                        email=NULL,
                        amount_cents=:amount,
                        currency=:currency,
                        stripe_payment_intent_id=COALESCE(:pi,stripe_payment_intent_id)
                    WHERE stripe_session_id=:sid
                    """
                ),
                params,
            )
        else:
            by_token = conn.execute(
                text("SELECT id,status FROM purchases WHERE access_token=:token"),
                {"token": _token_digest(access_token)},
            ).fetchone()
            if by_token:
                conn.execute(
                    text(
                        """
                        UPDATE purchases
                        SET stripe_session_id=:sid,
                            status=CASE WHEN status='pending' THEN 'paid' ELSE status END,
                            paid_at=COALESCE(paid_at,:paid),
                            email=NULL,
                            amount_cents=:amount,
                            currency=:currency,
                            stripe_payment_intent_id=COALESCE(:pi,stripe_payment_intent_id)
                        WHERE access_token=:token
                        """
                    ),
                    params,
                )
            else:
                conn.execute(
                    text(
                        """
                        INSERT INTO purchases(
                          access_token,email,status,amount_cents,currency,
                          stripe_session_id,stripe_payment_intent_id,
                          acquisition_json,created_at,paid_at
                        )
                        VALUES(:token,NULL,'paid',:amount,:currency,:sid,:pi,'{}',:created,:paid)
                        """
                    ),
                    params,
                )
    return get_purchase_by_session(session_id) or get_purchase_by_token(access_token)


def get_purchase_by_token(token: str) -> Optional[dict]:
    digest = _token_digest(token)
    with ENGINE.begin() as conn:
        row = conn.execute(
            text("SELECT * FROM purchases WHERE access_token=:digest OR access_token=:legacy"),
            {"digest": digest, "legacy": token},
        ).fetchone()
        if row and row._mapping["access_token"] == token:
            conn.execute(
                text("UPDATE purchases SET access_token=:digest WHERE id=:id"),
                {"digest": digest, "id": row._mapping["id"]},
            )
            row = conn.execute(
                text("SELECT * FROM purchases WHERE id=:id"),
                {"id": row._mapping["id"]},
            ).fetchone()
    return _rowdict(row)


def get_purchase_by_id(purchase_id: int) -> Optional[dict]:
    with ENGINE.connect() as conn:
        row = conn.execute(
            text("SELECT * FROM purchases WHERE id=:id"),
            {"id": purchase_id},
        ).fetchone()
    return _rowdict(row)


def get_purchases_by_ids(purchase_ids: list[int]) -> list[dict]:
    ids = [int(pid) for pid in purchase_ids if int(pid) > 0]
    if not ids:
        return []
    placeholders = ",".join(f":p{i}" for i in range(len(ids)))
    params = {f"p{i}": pid for i, pid in enumerate(ids)}
    with ENGINE.connect() as conn:
        rows = conn.execute(
            text(f"SELECT * FROM purchases WHERE id IN ({placeholders}) ORDER BY paid_at DESC, id DESC"),
            params,
        ).fetchall()
    return [_rowdict(row) for row in rows]


def get_purchase_by_session(session_id: str) -> Optional[dict]:
    with ENGINE.connect() as conn:
        row = conn.execute(
            text("SELECT * FROM purchases WHERE stripe_session_id=:sid"),
            {"sid": session_id},
        ).fetchone()
    return _rowdict(row)


def get_purchase_by_payment_intent(payment_intent_id: str) -> Optional[dict]:
    with ENGINE.connect() as conn:
        row = conn.execute(
            text("SELECT * FROM purchases WHERE stripe_payment_intent_id=:pi"),
            {"pi": payment_intent_id},
        ).fetchone()
    return _rowdict(row)


def mark_checkout_expired(session_id: str) -> bool:
    with ENGINE.begin() as conn:
        res = conn.execute(
            text(
                "UPDATE purchases SET status='expired' WHERE stripe_session_id=:sid AND status='pending'"
            ),
            {"sid": session_id},
        )
    return bool(res.rowcount)


def set_purchase_billing_state(
    payment_intent_id: str,
    status: str,
    revoked_reason: str | None,
) -> bool:
    if not payment_intent_id:
        return False
    revoked_at = now_iso() if revoked_reason else None
    with ENGINE.begin() as conn:
        res = conn.execute(
            text(
                """
                UPDATE purchases
                SET status=:status,
                    access_revoked_at=:revoked,
                    access_revoked_reason=:reason
                WHERE stripe_payment_intent_id=:pi
                """
            ),
            {
                "status": status,
                "revoked": revoked_at,
                "reason": revoked_reason,
                "pi": payment_intent_id,
            },
        )
    return bool(res.rowcount)


def revoke_purchase(purchase_id: int, reason: str) -> None:
    with ENGINE.begin() as conn:
        conn.execute(
            text(
                "UPDATE purchases SET access_revoked_at=:revoked, access_revoked_reason=:reason WHERE id=:id"
            ),
            {"revoked": now_iso(), "reason": reason, "id": purchase_id},
        )


def save_assessment(
    purchase_id: int,
    answers: dict,
    result: dict,
    consultation_fingerprint: str | None = None,
    consultation_fragment_fingerprints: list[str] | None = None,
):
    params = {
        "pid": purchase_id,
        "answers": encrypt_json(answers),
        "result": encrypt_json(result),
        "created": now_iso(),
    }
    with ENGINE.begin() as conn:
        existing = conn.execute(
            text("SELECT 1 FROM assessments WHERE purchase_id=:pid"),
            {"pid": purchase_id},
        ).fetchone()
        if existing:
            raise RuntimeError("Assessment already completed for this purchase")

        if consultation_fingerprint:
            inserted = conn.execute(
                text(
                    "INSERT INTO consultation_fingerprints(fingerprint,created_at) "
                    "VALUES(:fp,:created) ON CONFLICT(fingerprint) DO NOTHING"
                ),
                {"fp": consultation_fingerprint, "created": params["created"]},
            ).rowcount
            if not inserted:
                raise DuplicateConsultationFingerprint(
                    "Consultation content fingerprint already exists"
                )

        for fragment_fp in dict.fromkeys(consultation_fragment_fingerprints or []):
            inserted = conn.execute(
                text(
                    "INSERT INTO consultation_fragment_fingerprints(fingerprint,created_at) "
                    "VALUES(:fp,:created) ON CONFLICT(fingerprint) DO NOTHING"
                ),
                {"fp": fragment_fp, "created": params["created"]},
            ).rowcount
            if not inserted:
                raise DuplicateConsultationFingerprint(
                    "Consultation section fingerprint already exists"
                )

        conn.execute(
            text(
                "INSERT INTO assessments(purchase_id,answers_json,result_json,created_at) "
                "VALUES(:pid,:answers,:result,:created)"
            ),
            params,
        )
        conn.execute(
            text("DELETE FROM assessment_drafts WHERE purchase_id=:pid"),
            {"pid": purchase_id},
        )


def get_assessment_for_purchase(purchase_id: int) -> Optional[dict]:
    with ENGINE.connect() as conn:
        row = conn.execute(
            text("SELECT * FROM assessments WHERE purchase_id=:pid"),
            {"pid": purchase_id},
        ).fetchone()
    if not row:
        return None
    data = _rowdict(row)
    data["answers"] = decrypt_json(data.pop("answers_json"))
    data["result"] = decrypt_json(data.pop("result_json"))
    return data


def save_assessment_draft(purchase_id: int, answers: dict, current_index: int):
    params = {
        "pid": purchase_id,
        "answers": encrypt_json(answers),
        "idx": max(0, int(current_index)),
        "updated": now_iso(),
    }
    with ENGINE.begin() as conn:
        if DB_URL.startswith("sqlite:"):
            conn.execute(
                text(
                    """
                    INSERT INTO assessment_drafts(purchase_id,answers_json,current_index,updated_at)
                    VALUES(:pid,:answers,:idx,:updated)
                    ON CONFLICT(purchase_id) DO UPDATE SET
                      answers_json=excluded.answers_json,
                      current_index=excluded.current_index,
                      updated_at=excluded.updated_at
                    """
                ),
                params,
            )
        else:
            conn.execute(
                text(
                    """
                    INSERT INTO assessment_drafts(purchase_id,answers_json,current_index,updated_at)
                    VALUES(:pid,:answers,:idx,:updated)
                    ON CONFLICT(purchase_id) DO UPDATE SET
                      answers_json=EXCLUDED.answers_json,
                      current_index=EXCLUDED.current_index,
                      updated_at=EXCLUDED.updated_at
                    """
                ),
                params,
            )


def get_assessment_draft(purchase_id: int) -> Optional[dict]:
    with ENGINE.connect() as conn:
        row = conn.execute(
            text("SELECT * FROM assessment_drafts WHERE purchase_id=:pid"),
            {"pid": purchase_id},
        ).fetchone()
    if not row:
        return None
    data = _rowdict(row)
    data["answers"] = decrypt_json(data.pop("answers_json"))
    return data


def delete_assessment_draft(purchase_id: int):
    with ENGINE.begin() as conn:
        conn.execute(
            text("DELETE FROM assessment_drafts WHERE purchase_id=:pid"),
            {"pid": purchase_id},
        )


def save_feedback(purchase_id: int, day: int, payload: dict):
    params = {
        "pid": purchase_id,
        "day": day,
        "payload": encrypt_json(payload),
        "created": now_iso(),
    }
    with ENGINE.begin() as conn:
        if DB_URL.startswith("sqlite:"):
            conn.execute(
                text(
                    """
                    INSERT INTO feedback(purchase_id,day,payload_json,created_at)
                    VALUES(:pid,:day,:payload,:created)
                    ON CONFLICT(purchase_id,day) DO UPDATE SET
                      payload_json=excluded.payload_json,
                      created_at=excluded.created_at
                    """
                ),
                params,
            )
        else:
            conn.execute(
                text(
                    """
                    INSERT INTO feedback(purchase_id,day,payload_json,created_at)
                    VALUES(:pid,:day,:payload,:created)
                    ON CONFLICT(purchase_id,day) DO UPDATE SET
                      payload_json=EXCLUDED.payload_json,
                      created_at=EXCLUDED.created_at
                    """
                ),
                params,
            )


def privacy_maintenance(retention_days: int) -> dict:
    """Encrypt legacy rows, scrub local contact data, and expire private content."""
    cutoff = (datetime.now(timezone.utc) - timedelta(days=retention_days)).isoformat()
    encrypted = 0
    with ENGINE.begin() as conn:
        rows = conn.execute(
            text("SELECT id, answers_json, result_json FROM assessments")
        ).fetchall()
        for row in rows:
            m = row._mapping
            answers_raw = m["answers_json"]
            result_raw = m["result_json"]
            if not str(answers_raw).startswith("fernet:") or not str(result_raw).startswith("fernet:"):
                conn.execute(
                    text(
                        "UPDATE assessments SET answers_json=:answers, result_json=:result WHERE id=:id"
                    ),
                    {
                        "answers": encrypt_json(decrypt_json(answers_raw)),
                        "result": encrypt_json(decrypt_json(result_raw)),
                        "id": m["id"],
                    },
                )
                encrypted += 1

        feedback_rows = conn.execute(
            text("SELECT id, payload_json FROM feedback")
        ).fetchall()
        for row in feedback_rows:
            m = row._mapping
            raw = m["payload_json"]
            if not str(raw).startswith("fernet:"):
                conn.execute(
                    text("UPDATE feedback SET payload_json=:payload WHERE id=:id"),
                    {"payload": encrypt_json(json.loads(raw)), "id": m["id"]},
                )

        draft_rows = conn.execute(
            text("SELECT purchase_id, answers_json FROM assessment_drafts")
        ).fetchall()
        for row in draft_rows:
            m = row._mapping
            raw = m["answers_json"]
            if not str(raw).startswith("fernet:"):
                conn.execute(
                    text(
                        "UPDATE assessment_drafts SET answers_json=:answers WHERE purchase_id=:pid"
                    ),
                    {
                        "answers": encrypt_json(json.loads(raw)),
                        "pid": m["purchase_id"],
                    },
                )

        token_rows = conn.execute(
            text("SELECT id, access_token FROM purchases")
        ).fetchall()
        legacy_tokens_hashed = 0
        for row in token_rows:
            m = row._mapping
            token_value = str(m["access_token"])
            if not token_value.startswith("sha256:"):
                conn.execute(
                    text("UPDATE purchases SET access_token=:digest WHERE id=:id"),
                    {"digest": _token_digest(token_value), "id": m["id"]},
                )
                legacy_tokens_hashed += 1

        scrubbed = conn.execute(
            text("UPDATE purchases SET email=NULL WHERE email IS NOT NULL")
        ).rowcount or 0

        # Expiration is tied to the purchase window, not to the day the report happened to be generated.
        expired_ids = conn.execute(
            text(
                """
                SELECT id FROM purchases
                WHERE COALESCE(paid_at,created_at) < :cutoff
                """
            ),
            {"cutoff": cutoff},
        ).fetchall()
        ids = [row._mapping["id"] for row in expired_ids]

        feedback_deleted = assessments_deleted = drafts_deleted = 0
        for purchase_id in ids:
            feedback_deleted += conn.execute(
                text("DELETE FROM feedback WHERE purchase_id=:pid"),
                {"pid": purchase_id},
            ).rowcount or 0
            assessments_deleted += conn.execute(
                text("DELETE FROM assessments WHERE purchase_id=:pid"),
                {"pid": purchase_id},
            ).rowcount or 0
            drafts_deleted += conn.execute(
                text("DELETE FROM assessment_drafts WHERE purchase_id=:pid"),
                {"pid": purchase_id},
            ).rowcount or 0

    return {
        "legacy_assessments_encrypted": encrypted,
        "legacy_access_tokens_hashed": legacy_tokens_hashed,
        "purchase_emails_scrubbed": scrubbed,
        "expired_feedback_deleted": feedback_deleted,
        "expired_assessments_deleted": assessments_deleted,
        "expired_drafts_deleted": drafts_deleted,
    }


def consultation_fingerprint_exists(fingerprint: str) -> bool:
    with ENGINE.connect() as conn:
        row = conn.execute(
            text("SELECT 1 FROM consultation_fingerprints WHERE fingerprint=:fp"),
            {"fp": fingerprint},
        ).fetchone()
    return bool(row)


def get_recent_consultation_texts(limit: int = 500) -> list[str]:
    """Return decrypted consultation bodies for similarity checking only."""
    from .consultation import consultation_text

    texts: list[str] = []
    with ENGINE.connect() as conn:
        rows = conn.execute(
            text("SELECT result_json FROM assessments ORDER BY created_at DESC LIMIT :limit"),
            {"limit": max(1, min(int(limit), 500))},
        ).fetchall()

    for row in rows:
        try:
            result = decrypt_json(row._mapping["result_json"])
            consultation = result.get("_consultation") if isinstance(result, dict) else None
            if consultation:
                body = consultation_text(consultation)
                if body:
                    texts.append(body)
        except Exception:
            continue
    return texts


def delete_personal_data(purchase_id: int) -> dict:
    """Delete consultation data and revoke the entitlement while retaining the transaction."""
    with ENGINE.begin() as conn:
        feedback_deleted = conn.execute(
            text("DELETE FROM feedback WHERE purchase_id=:pid"),
            {"pid": purchase_id},
        ).rowcount or 0
        assessments_deleted = conn.execute(
            text("DELETE FROM assessments WHERE purchase_id=:pid"),
            {"pid": purchase_id},
        ).rowcount or 0
        drafts_deleted = conn.execute(
            text("DELETE FROM assessment_drafts WHERE purchase_id=:pid"),
            {"pid": purchase_id},
        ).rowcount or 0
        conn.execute(
            text(
                """
                UPDATE purchases
                SET email=NULL,
                    acquisition_json='{}',
                    access_revoked_at=:revoked,
                    access_revoked_reason='customer_deleted'
                WHERE id=:pid
                """
            ),
            {"pid": purchase_id, "revoked": now_iso()},
        )
    return {
        "feedback_deleted": feedback_deleted,
        "assessments_deleted": assessments_deleted,
        "drafts_deleted": drafts_deleted,
    }


def admin_summary() -> dict:
    with ENGINE.connect() as conn:
        p = conn.execute(
            text(
                """
                SELECT
                  COUNT(*) AS total,
                  SUM(CASE WHEN status='paid' THEN 1 ELSE 0 END) AS paid,
                  SUM(CASE WHEN status='refunded' THEN 1 ELSE 0 END) AS refunded,
                  SUM(CASE WHEN status='disputed' THEN 1 ELSE 0 END) AS disputed,
                  SUM(CASE WHEN status='paid' THEN amount_cents ELSE 0 END) AS revenue_cents
                FROM purchases
                """
            )
        ).fetchone()
        a = conn.execute(text("SELECT COUNT(*) AS total FROM assessments")).fetchone()
        f = conn.execute(
            text("SELECT day, COUNT(*) AS c FROM feedback GROUP BY day ORDER BY day")
        ).fetchall()

    pm = p._mapping
    total = pm["total"] or 0
    paid = pm["paid"] or 0
    assessments = a._mapping["total"] or 0
    return {
        "purchases": total,
        "paid": paid,
        "refunded": pm["refunded"] or 0,
        "disputed": pm["disputed"] or 0,
        "revenue_cents": pm["revenue_cents"] or 0,
        "assessment_completions": assessments,
        "paid_to_assessment_rate": round((assessments / paid * 100), 1) if paid else 0,
        "feedback": {str(row._mapping["day"]): row._mapping["c"] for row in f},
    }
